// <auto-generated />
namespace ProductsEntityModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Criando_o_Banco : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Criando_o_Banco));
        
        string IMigrationMetadata.Id
        {
            get { return "202111202135553_Criando_o_Banco"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
